# This is a basic workflow to help you get started with Actions
name: x86-64
on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Set the firmware size (in MB).'
        required: true
        default: '2048'
      include_docker:
        description: |
          Enable Docker 
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "Enable PPPoE"
        required: true
        default: 'no'
        type: choice
        options:
        - 'yes'
        - 'no'
      pppoe_account:
        description: "Broadband Account "
        required: false
      pppoe_password:
        description: "Broadand Password"
        required: false
